import mongoose from "mongoose";

/**
 * Blog Post Model (extended for automation pipeline)
 *
 * Original fields preserved for manual/CMS posts.
 * Automation fields added as optional — existing posts unaffected.
 *
 * Status flow (automation):
 *   draft → pending_review → approved → published
 *   Any stage can go → failed
 *   rejected → goes back to content stage with new angle
 */
const blogSchema = new mongoose.Schema(
  {
    // ── Core fields (original) ───────────────────────────────────────────────
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: [200, "Title cannot be longer than 200 characters"],
    },
    content: {
      type: String,
      required: [true, "Content is required"],
    },
    author: {
      type: String,
      required: [true, "Author is required"],
      trim: true,
      maxlength: [100, "Author name cannot be longer than 100 characters"],
      default: "Cloudvyn AI",
    },
    slug: {
      type: String,
      required: [true, "Slug is required"],
      unique: true,
      lowercase: true,
      trim: true,
      validate: {
        validator: function (v) {
          return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(v);
        },
        message: "Slug can only contain lowercase letters, numbers, and hyphens.",
      },
    },
    oldSlugs: [{ type: String }],
    tags: {
      type: [String],
      default: [],
    },
    category: {
      type: String,
    },
    image: {
      type: String,
      validate: {
        validator: function (v) {
          return !v || /^(https?|ftp):\/\/[^\s/$.?#].[^\s]*$/.test(v);
        },
        message: "Invalid image URL",
      },
    },

    // ── Automation pipeline fields ───────────────────────────────────────────

    // The seed keyword this post was generated from
    keyword: {
      type: String,
      trim: true,
      lowercase: true,
      default: null,
    },

    // Reference to keywords collection entry
    keyword_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "keyword",
      default: null,
    },

    // Short meta description (160 chars) — used for og:description, SEO
    meta: {
      type: String,
      maxlength: [320, "Meta description too long"],
      default: null,
    },

    // GCS URL of AI-generated cover image
    cover_image_url: {
      type: String,
      default: null,
    },

    // Originality.ai scores (0–100)
    plagiarism_score: {
      type: Number,
      min: 0,
      max: 100,
      default: null,
    },
    ai_score: {
      type: Number,
      min: 0,
      max: 100,
      default: null,
    },

    // Full SEO metadata object
    seo_meta: {
      title_tag: { type: String, default: null },
      canonical_url: { type: String, default: null },
      og_title: { type: String, default: null },
      og_description: { type: String, default: null },
      og_image: { type: String, default: null },
      schema_markup: { type: mongoose.Schema.Types.Mixed, default: null },
      internal_links: [{ anchor: String, url: String }],
    },

    // NOTE: WordPress is not used — posts are served by the custom frontend.
    // wp_id is kept as null/optional for future reference only.
    wp_id: {
      type: Number,
      default: null,
    },

    // Extended status enum for automation pipeline
    status: {
      type: String,
      enum: [
        "draft",           // Content generated, not reviewed
        "pending_review",  // Awaiting human approval (Telegram / dashboard)
        "approved",        // Human approved — ready for SEO finalization
        "rejected",        // Human rejected — will regenerate with new angle
        "published",       // Live on WordPress
        "failed",          // Pipeline error — check jobs collection
      ],
      default: "draft",
      index: true,
    },

    // True if this was created by the automation pipeline
    is_automated: {
      type: Boolean,
      default: false,
    },

    // Original content snapshot before any edits (for retry comparison)
    content_original: {
      type: String,
      default: null,
    },

    // Retry angle hints for content regeneration
    rejection_notes: {
      type: String,
      default: null,
    },

    // How many times content was regenerated
    content_retry_count: {
      type: Number,
      default: 0,
    },

    // Alternative titles generated by LLM
    alt_titles: {
      type: [String],
      default: [],
    },

    // FAQ section (array of {question, answer})
    faqs: [
      {
        question: { type: String },
        answer: { type: String },
      },
    ],

    published_at: {
      type: Date,
      default: null,
    },

    indexed_at: {
      type: Date,
      default: null,
    },
  },
  { timestamps: true }
);

// Full-text search index
blogSchema.index({ title: "text", content: "text", tags: "text", keyword: "text" });
// Pipeline queries
blogSchema.index({ status: 1, is_automated: 1, createdAt: -1 });

export default mongoose.model("blog_post", blogSchema);